protobuf.lo: /home/liuxu/source/protobuf/php-protobuf-0.12.4/protobuf.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/liuxu/source/protobuf/php-protobuf-0.12.4 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/liuxu/source/protobuf/php-protobuf-0.12.4/protobuf.c -o protobuf.lo 
reader.lo: /home/liuxu/source/protobuf/php-protobuf-0.12.4/reader.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/liuxu/source/protobuf/php-protobuf-0.12.4 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/liuxu/source/protobuf/php-protobuf-0.12.4/reader.c -o reader.lo 
writer.lo: /home/liuxu/source/protobuf/php-protobuf-0.12.4/writer.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/liuxu/source/protobuf/php-protobuf-0.12.4 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/liuxu/source/protobuf/php-protobuf-0.12.4/writer.c -o writer.lo 
$(phplibdir)/protobuf.la: ./protobuf.la
	$(LIBTOOL) --mode=install cp ./protobuf.la $(phplibdir)

./protobuf.la: $(shared_objects_protobuf) $(PROTOBUF_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_protobuf) $(PROTOBUF_SHARED_LIBADD)

